### ISSUE TITLE
RuntimeError: Expected object of scalar type double but got scalar type float for sequence element 1.

### ISSUE THREAD

**Issue by jasonkey** [cryogen-project/cryogen#215]
Hi Ellen, 

We see this error with the command below. 
It appears to be reproducible, we have seen it on a couple of runs now. 
Looks like a possible bug to me, let me know if we can provide more info.

`$ cryodrgn analyze 00_vae128_z1 49 --Apix 0.85`

```
2020-05-15 12:20:12     Saving results to /nfs/lcemdata/fischer/mhunkeler/20190204_krios_hms/DRGN/00_vae128_z1/analyze.49

2020-05-15 12:20:16     Running command:

cryodrgn eval_vol /nfs/lcemdata/fischer/mhunkeler/20190204_krios_hms/DRGN/00_vae128_z1/weights.49.pkl --config /nfs/lcemdata/fischer/mhunkeler/20190204_krios_hms/DRGN/00_vae128_z1/config.pkl --zfile /nfs/lcemdata/fischer/mhunkeler/20190204_krios_hms/DRGN/00_vae128_z1/analyze.49/z_values.txt -o /nfs/lcemdata/fischer/mhunkeler/20190204_krios_hms/DRGN/00_vae128_z1/analyze.49 --Apix 0.85

2020-05-15 12:20:21     Use cuda True

2020-05-15 12:20:21     Namespace(Apix=0.85, D=128, config='/nfs/lcemdata/fischer/mhunkeler/20190204_krios_hms/DRGN/00_vae128_z1/config.pkl', domain='fourier', downsample=None, enc_mask=64, encode_mode='resid', flip=False, func=<function main at 0x7f38212e13b0>, l_extent=0.5, n=10, norm=[0, 480.96075], o='/nfs/lcemdata/fischer/mhunkeler/20190204_krios_hms/DRGN/00_vae128_z1/analyze.49', pdim=256, pe_type='geom_lowf', players=3, prefix='vol_', qdim=256, qlayers=3, verbose=False, weights='/nfs/lcemdata/fischer/mhunkeler/20190204_krios_hms/DRGN/00_vae128_z1/weights.49.pkl', z=None, z_end=None, z_start=None, zdim=1, zfile='/nfs/lcemdata/fischer/mhunkeler/20190204_krios_hms/DRGN/00_vae128_z1/analyze.49/z_values.txt')

2020-05-15 12:20:26     Using circular lattice with radius 64

2020-05-15 12:20:26     Loading weights from /nfs/lcemdata/fischer/mhunkeler/20190204_krios_hms/DRGN/00_vae128_z1/weights.49.pkl

2020-05-15 12:20:27     Generating 10 volumes

2020-05-15 12:20:27     [-1.62018406]

Traceback (most recent call last):

  File "/programs/x86_64-linux//cryodrgn/0.2.0/cryodrgn/bin/cryodrgn", line 11, in <module>

    load_entry_point('cryodrgn==0.2.0', 'console_scripts', 'cryodrgn')()

  File "/programs/x86_64-linux/cryodrgn/0.2.0/cryodrgn_extlib/miniconda3-4.7.12.1-2tlz/lib/python3.7/site-packages/cryodrgn-0.2.0-py3.7.egg/cryodrgn/__main__.py", line 50, in main

    args.func(args)

  File "/programs/x86_64-linux/cryodrgn/0.2.0/cryodrgn_extlib/miniconda3-4.7.12.1-2tlz/lib/python3.7/site-packages/cryodrgn-0.2.0-py3.7.egg/cryodrgn/commands/eval_vol.py", line 120, in main

    vol = model.decoder.eval_volume(lattice.coords, lattice.D, lattice.extent, args.norm, zz)

  File "/programs/x86_64-linux/cryodrgn/0.2.0/cryodrgn_extlib/miniconda3-4.7.12.1-2tlz/lib/python3.7/site-packages/cryodrgn-0.2.0-py3.7.egg/cryodrgn/models.py", line 299, in eval_volume

    x = torch.cat((x,z), dim=-1)

RuntimeError: Expected object of scalar type double but got scalar type float for sequence element 1.

Traceback (most recent call last):

  File "/programs/x86_64-linux//cryodrgn/0.2.0/cryodrgn/bin/cryodrgn", line 11, in <module>

    load_entry_point('cryodrgn==0.2.0', 'console_scripts', 'cryodrgn')()

  File "/programs/x86_64-linux/cryodrgn/0.2.0/cryodrgn_extlib/miniconda3-4.7.12.1-2tlz/lib/python3.7/site-packages/cryodrgn-0.2.0-py3.7.egg/cryodrgn/__main__.py", line 50, in main

    args.func(args)

  File "/programs/x86_64-linux/cryodrgn/0.2.0/cryodrgn_extlib/miniconda3-4.7.12.1-2tlz/lib/python3.7/site-packages/cryodrgn-0.2.0-py3.7.egg/cryodrgn/commands/analyze.py", line 159, in main

    analyze_z1(z, outdir, vg)

  File "/programs/x86_64-linux/cryodrgn/0.2.0/cryodrgn_extlib/miniconda3-4.7.12.1-2tlz/lib/python3.7/site-packages/cryodrgn-0.2.0-py3.7.egg/cryodrgn/commands/analyze.py", line 55, in analyze_z1

    vg.gen_volumes(outdir, ztraj)

  File "/programs/x86_64-linux/cryodrgn/0.2.0/cryodrgn_extlib/miniconda3-4.7.12.1-2tlz/lib/python3.7/site-packages/cryodrgn-0.2.0-py3.7.egg/cryodrgn/commands/analyze.py", line 131, in gen_volumes

    analysis.gen_volumes(self.weights, self.config, zfile, outdir, **self.vol_args)

  File "/programs/x86_64-linux/cryodrgn/0.2.0/cryodrgn_extlib/miniconda3-4.7.12.1-2tlz/lib/python3.7/site-packages/cryodrgn-0.2.0-py3.7.egg/cryodrgn/analysis.py", line 292, in gen_volumes

    return subprocess.check_call(cmd, shell=True)

  File "/programs/x86_64-linux/cryodrgn/0.2.0/cryodrgn_extlib/miniconda3-4.7.12.1-2tlz/lib/python3.7/subprocess.py", line 347, in check_call

    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command 'cryodrgn eval_vol /nfs/lcemdata/fischer/mhunkeler/20190204_krios_hms/DRGN/00_vae128_z1/weights.49.pkl --config /nfs/lcemdata/fischer/mhunkeler/20190204_krios_hms/DRGN/00_vae128_z1/config.pkl --zfile /nfs/lcemdata/fischer/mhunkeler/20190204_krios_hms/DRGN/00_vae128_z1/analyze.49/z_values.txt -o /nfs/lcemdata/fischer/mhunkeler/20190204_krios_hms/DRGN/00_vae128_z1/analyze.49 --Apix 0.85' returned non-zero exit status 1.

perl: warning: Setting locale failed.

perl: warning: Please check that your locale settings:

    LANGUAGE = (unset),

    LC_ALL = (unset),

    LC_CTYPE = "UTF-8",

    LANG = "en_US.UTF-8"

    are supported and installed on your system.

perl: warning: Falling back to the standard locale ("C").

 DRGN$
```

**Comment by lacarmen** [comment]
Wrong repo? 😛 

https://github.com/zhonge/cryodrgn

**Comment by jasonkey** [comment]
Yep, wrong repo. 
Not sure how I did that exactly, thanks for the quick reply. 

issue closed 😄
